#!/usr/bin/env python3
import sys
import webbrowser
import pyautogui as p
from time import sleep

def main(args):
    website = args[0]
    for i in range(10):
        webbrowser.open(website)
        sleep(1)
        hacker_txt = 'attempt' + str(i)
        p.click(918,429)
        for _ in range(10):
            p.typewrite(hacker_txt)
            p.press('tab')
        #x:1244 y:870 
        p.click(1244,870)
        #p.press('enter')
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
